### ISSUE TITLE
E1107 10:32:56.402884643   12884 ssl_transport_security.cc:1227] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by Smy0521** [TrustedBlockchain/TrustedBench_test#4]
E1107 10:32:56.402884643   12884 ssl_transport_security.cc:1227] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: Connect Failed\n    at Object.exports.createStatusError (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/common.js:87:15)\n    at ClientDuplexStream._emitStatusIfDone (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client.js:235:26)\n    at ClientDuplexStream._receiveStatus (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client.js:213:8)\n    at Object.onReceiveStatus (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1290:15)\n    at InterceptingListener._callNext (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:564:42)\n    at InterceptingListener.onReceiveStatus (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:614:8)\n    at /home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1110:18"
not ok 1 Failed to create channels Error: SERVICE_UNAVAILABLE at ClientDuplexStream.<anonymous> (/home/mpsp/TrustedBench/node_modules/fabric-client/lib/Orderer.js:136:21) at ClientDuplexStream.emit (events.js:182:13) at ClientDuplexStream._emitStatusIfDone (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client.js:236:12) at ClientDuplexStream._receiveStatus (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client.js:213:8) at Object.onReceiveStatus (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1290:15) at InterceptingListener._callNext (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:564:42) at InterceptingListener.onReceiveStatus (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:614:8) at /home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1110:18
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/home/mpsp/TrustedBench/src/fabric/create-channel.js:159:19)
    stack: |-
      Error: Failed to create channels Error: SERVICE_UNAVAILABLE
          at ClientDuplexStream.<anonymous> (/home/mpsp/TrustedBench/node_modules/fabric-client/lib/Orderer.js:136:21)
          at ClientDuplexStream.emit (events.js:182:13)
          at ClientDuplexStream._emitStatusIfDone (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client.js:236:12)
          at ClientDuplexStream._receiveStatus (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client.js:213:8)
          at Object.onReceiveStatus (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1290:15)
          at InterceptingListener._callNext (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:564:42)
          at InterceptingListener.onReceiveStatus (/home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:614:8)
          at /home/mpsp/TrustedBench/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1110:18
          at Test.assert [as _assert] (/home/mpsp/TrustedBench/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/mpsp/TrustedBench/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/mpsp/TrustedBench/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/mpsp/TrustedBench/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/home/mpsp/TrustedBench/src/fabric/create-channel.js:159:19)
          at process._tickCallback (internal/process/next_tick.js:68:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/mpsp/TrustedBench/src/fabric/create-channel.js:160:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
unexpected error, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/mpsp/TrustedBench/src/fabric/create-channel.js:160:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev* -q)
E1107 10:32:57.397643591   12884 ssl_transport_security.cc:1227] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
Stopping peer0.org1.example.com ... 
Stopping peer1.org1.example.com ... 
Stopping peer0.org1.example.com ... done
Stopping peer1.org1.example.com ... done
Stopping peer0.org2.example.com ... done
Stopping peer1.org2.example.com ... done
Stopping orderer.example.com    ... done
Stopping ca_peerOrg1            ... 
E1107 10:32:59.269281891   12884 ssl_transport_security.cc:1227] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.

**Comment by Smy0521** [comment]
I set the node version to v8.9.0 benchmark success

nvm install  v8.9.0
